// Phase 1 placeholder.
// Phase 2 replaces this with the actual Black lexer/parser input pipeline.

import { readFile, rm, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Diagnostic } from "../white/output/diagnostics.js";

export interface CompileRequest {
  projectRoot: string;
  entryPath: string;
  outDir: string;
}

export interface Artifact {
  path: string;
  kind: "module";
}

export interface CompileResult {
  artifacts: Artifact[];
  diagnostics: Diagnostic[];
}

export const PHASE_1_MARKER = "Black preview pipeline alive.";

export async function compile(request: CompileRequest): Promise<CompileResult> {
  // Consume the entry so the build genuinely reads it — even though its
  // contents do not yet determine the output.
  await readFile(request.entryPath, "utf8");

  await rm(request.outDir, { recursive: true, force: true });
  await mkdir(request.outDir, { recursive: true });

  const outPath = path.join(request.outDir, "main.mjs");
  const source = `// Generated by White (preview-web-1) — Phase 1 placeholder output.\nconsole.log(${JSON.stringify(PHASE_1_MARKER)});\n`;
  await writeFile(outPath, source, "utf8");

  return {
    artifacts: [{ path: outPath, kind: "module" }],
    diagnostics: [],
  };
}
