// Compiler entry point.
//
// Phase 2 replaces the Phase 1 fake front end with a real lexer + layout +
// parser pipeline. The backend still emits a fixed placeholder JavaScript
// artifact — genuine Black-to-JavaScript emission is Phase 5's responsibility.
// The important contract for Phase 2 is: source that does not parse cannot
// reach the backend.

import { readFile, rm, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Diagnostic } from "../white/output/diagnostics.js";
import { codes, makeDiagnostic } from "../white/output/diagnostics.js";
import { makeSourceFile, toDiagnosticSpan } from "./source.js";
import { parseModule, type ParseDiagnostic } from "./parser.js";
import type { Module } from "./ast.js";

export interface CompileRequest {
  projectRoot: string;
  entryPath: string;
  outDir: string;
}

export interface Artifact {
  path: string;
  kind: "module";
}

export interface CompileResult {
  ok: boolean;
  parsedModule: Module | null;
  artifacts: Artifact[];
  diagnostics: Diagnostic[];
}

export interface ParseOnlyRequest {
  entryPath: string;
}

export interface ParseOnlyResult {
  ok: boolean;
  module: Module | null;
  diagnostics: Diagnostic[];
}

export const PHASE_1_MARKER = "Black preview pipeline alive.";

export async function parseSource(request: ParseOnlyRequest): Promise<ParseOnlyResult> {
  const text = await readFile(request.entryPath, "utf8");
  const source = makeSourceFile(request.entryPath, text);
  const result = parseModule(source);
  const diagnostics = result.diagnostics.map((d) => toWhiteDiagnostic(d, request.entryPath));
  return {
    ok: result.diagnostics.length === 0 && result.module !== null,
    module: result.module,
    diagnostics,
  };
}

export async function compile(request: CompileRequest): Promise<CompileResult> {
  const parseResult = await parseSource({ entryPath: request.entryPath });

  if (!parseResult.ok) {
    return {
      ok: false,
      parsedModule: null,
      artifacts: [],
      diagnostics: parseResult.diagnostics,
    };
  }

  // Parse succeeded. Emit the placeholder artifact.
  await rm(request.outDir, { recursive: true, force: true });
  await mkdir(request.outDir, { recursive: true });

  const outPath = path.join(request.outDir, "main.mjs");
  const emission = `// Generated by White (preview-web-1) — Phase 2 emits the same placeholder artifact as Phase 1; real Black-to-JavaScript emission belongs to Phase 5.\nconsole.log(${JSON.stringify(PHASE_1_MARKER)});\n`;
  await writeFile(outPath, emission, "utf8");

  return {
    ok: true,
    parsedModule: parseResult.module,
    artifacts: [{ path: outPath, kind: "module" }],
    diagnostics: [],
  };
}

function toWhiteDiagnostic(d: ParseDiagnostic, file: string): Diagnostic {
  const kind = d.code.startsWith("BLACK_LEX_") ? "lex" : "parse";
  const code = mapDiagnosticCode(d.code);
  return makeDiagnostic({
    code,
    kind,
    severity: "error",
    message: d.message,
    file,
    span: toDiagnosticSpan(d.span),
  });
}

function mapDiagnosticCode(code: ParseDiagnostic["code"]): string {
  switch (code) {
    case "BLACK_LEX_INVALID_CHARACTER": return codes.lexInvalidCharacter;
    case "BLACK_LEX_INVALID_NUMBER": return codes.lexInvalidNumber;
    case "BLACK_LEX_UNTERMINATED_STRING": return codes.lexUnterminatedString;
    case "BLACK_LEX_INVALID_ESCAPE": return codes.lexInvalidEscape;
    case "BLACK_PARSE_UNEXPECTED_TOKEN": return codes.parseUnexpectedToken;
    case "BLACK_PARSE_UNEXPECTED_EOF": return codes.parseUnexpectedEof;
    case "BLACK_PARSE_TRAILING_TOKENS": return codes.parseTrailingTokens;
    case "BLACK_PARSE_LAYOUT_ERROR": return codes.parseLayoutError;
    case "BLACK_PARSE_UNSUPPORTED_SYNTAX": return codes.parseUnsupportedSyntax;
  }
}
